#!/bin/bash
# Generate build provenance environment variables for docker-compose.
#
# Called by devcontainer.json initializeCommand before every container build.
# Merges BUILD_* variables into the project .env file (which docker-compose
# auto-reads for variable substitution in docker-compose.yml).
#
# This ensures BUILD_* args (commit, branch, tag, date, hostname) contain real
# values instead of "unknown" when rebuilding via VS Code.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${PROJECT_ROOT}/.env"

# Compute provenance (same logic as build-base.sh)
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
BUILD_HOSTNAME=$(hostname -s 2>/dev/null || echo "unknown")

if git -C "$PROJECT_ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    BUILD_COMMIT=$(git -C "$PROJECT_ROOT" rev-parse --short=7 HEAD 2>/dev/null || echo "unknown")
    BUILD_BRANCH=$(git -C "$PROJECT_ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

    # Append -dirty suffix if there are uncommitted changes
    if ! git -C "$PROJECT_ROOT" diff --quiet HEAD 2>/dev/null \
       || ! git -C "$PROJECT_ROOT" diff --cached --quiet HEAD 2>/dev/null; then
        BUILD_COMMIT="${BUILD_COMMIT}-dirty"
    fi

    # Try to get a version tag
    BUILD_TAG=$(git -C "$PROJECT_ROOT" describe --exact-match --tags 2>/dev/null || echo "dev")
else
    BUILD_COMMIT="unknown"
    BUILD_BRANCH="unknown"
    BUILD_TAG="dev"
fi

# ---------------------------------------------------------------------------
# Merge BUILD_* variables into .env
#
# Strategy: strip any existing BUILD_* lines, then append fresh values.
# This preserves all other user-defined variables (GIT_USER_*, REGISTRY_*, etc.)
# ---------------------------------------------------------------------------

BUILD_VARS="BUILD_COMMIT BUILD_DATE BUILD_BRANCH BUILD_TAG BUILD_HOSTNAME"

if [ -f "$ENV_FILE" ]; then
    # Remove existing BUILD_* lines and the provenance header comment
    tmp=$(mktemp)
    grep -v -E "^(BUILD_COMMIT|BUILD_DATE|BUILD_BRANCH|BUILD_TAG|BUILD_HOSTNAME)=" "$ENV_FILE" \
        | grep -v "^# Build provenance" \
        > "$tmp" || true
    mv "$tmp" "$ENV_FILE"
else
    touch "$ENV_FILE"
fi

# Remove trailing blank lines, then ensure exactly one trailing newline
sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$ENV_FILE" 2>/dev/null || true
[ -s "$ENV_FILE" ] && echo >> "$ENV_FILE"

# Append provenance block
cat >> "$ENV_FILE" <<EOF
# Build provenance (auto-generated by .devcontainer/generate-build-env.sh)
BUILD_COMMIT=${BUILD_COMMIT}
BUILD_DATE=${BUILD_DATE}
BUILD_BRANCH=${BUILD_BRANCH}
BUILD_TAG=${BUILD_TAG}
BUILD_HOSTNAME=${BUILD_HOSTNAME}
EOF

echo "Build provenance written to .env:"
echo "  BUILD_COMMIT=${BUILD_COMMIT}"
echo "  BUILD_BRANCH=${BUILD_BRANCH}"
echo "  BUILD_TAG=${BUILD_TAG}"
echo "  BUILD_DATE=${BUILD_DATE}"
echo "  BUILD_HOSTNAME=${BUILD_HOSTNAME}"
